# --- Sample dataset

# --- !Ups

insert into company (id,name) values (  1,'Apple Inc.');
insert into company (id,name) values (  2,'Thinking Machines');
insert into company (id,name) values (  3,'RCA');
insert into company (id,name) values (  4,'Netronics');
insert into company (id,name) values (  5,'Tandy Corporation');
insert into company (id,name) values (  6,'Commodore International');
insert into company (id,name) values (  7,'MOS Technology');
insert into company (id,name) values (  8,'Micro Instrumentation and Telemetry Systems');
insert into company (id,name) values (  9,'IMS Associates, Inc.');
insert into company (id,name) values ( 10,'Digital Equipment Corporation');
insert into company (id,name) values ( 11,'Lincoln Laboratory');
insert into company (id,name) values ( 12,'Moore School of Electrical Engineering');
insert into company (id,name) values ( 13,'IBM');
insert into company (id,name) values ( 14,'Amiga Corporation');
insert into company (id,name) values ( 15,'Canon');
insert into company (id,name) values ( 16,'Nokia');
insert into company (id,name) values ( 17,'Sony');
insert into company (id,name) values ( 18,'OQO');
insert into company (id,name) values ( 19,'NeXT');    
insert into company (id,name) values ( 20,'Atari');
insert into company (id,name) values ( 22,'Acorn computer');
insert into company (id,name) values ( 23,'Timex Sinclair');
insert into company (id,name) values ( 24,'Nintendo');
insert into company (id,name) values ( 25,'Sinclair Research Ltd');
insert into company (id,name) values ( 26,'Xerox');
insert into company (id,name) values ( 27,'Hewlett-Packard');
insert into company (id,name) values ( 28,'Zemmix');
insert into company (id,name) values ( 29,'ACVS');
insert into company (id,name) values ( 30,'Sanyo');
insert into company (id,name) values ( 31,'Cray');
insert into company (id,name) values ( 32,'Evans & Sutherland');    
insert into company (id,name) values ( 33,'E.S.R. Inc.');
insert into company (id,name) values ( 34,'OMRON');
insert into company (id,name) values ( 35,'BBN Technologies');
insert into company (id,name) values ( 36,'Lenovo Group');
insert into company (id,name) values ( 37,'ASUS');
insert into company (id,name) values ( 38,'Amstrad');
insert into company (id,name) values ( 39,'Sun Microsystems');
insert into company (id,name) values ( 40,'Texas Instruments');
insert into company (id,name) values ( 41,'HTC Corporation');
insert into company (id,name) values ( 42,'Research In Motion');
insert into company (id,name) values ( 43,'Samsung Electronics');

insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook Pro 15.4 inch',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CM-2a',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CM-200',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CM-5e',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CM-5','1991-01-01',null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook Pro','2006-01-10',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple IIe',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple IIc',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple IIGS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple IIc Plus',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple II Plus',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple III','1980-05-01','1984-04-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple Lisa',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CM-2',null,null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Connection Machine','1987-01-01',null,2);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple II','1977-04-01','1993-10-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple III Plus','1983-12-01','1984-04-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'COSMAC ELF',null,null,3);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'COSMAC VIP','1977-01-01',null,3);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ELF II','1977-01-01',null,4);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh','1984-01-24',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh II',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Plus','1986-01-16','1990-10-15',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh IIfx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iMac','1998-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Mac Mini','2005-01-22',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Mac Pro','2006-08-07',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh','1994-03-01','2006-08-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook','1991-01-01','2006-01-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Xserve',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Powerbook 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Powerbook 140',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Powerbook 170',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook Duo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 190',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra','1991-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 700',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh LC','1990-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh LC II','1990-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh LC III','1993-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh LC III+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 605','1993-10-21',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh LC 500 series',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TRS-80 Color Computer','1980-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Acorn System 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Dragon 32/64',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MEK6800D2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Newbear 77/68',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore PET',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore 64','1982-08-01','1994-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore 64C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore SX-64',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore 128',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple I','1976-04-01','1977-10-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'KIM-1','1975-01-01',null,7);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Altair 8800','1974-12-19',null,8);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IMSAI 8080','1975-08-01',null,9);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IMSAI Series Two',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'VAX','1977-10-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'VAX 11/780','1977-10-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'VAX 11/750','1980-10-01',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TX-2','1958-01-01',null,11);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TX-0','1956-01-01',null,11);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Whirlwind','1951-04-20',null,11);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ENIAC','1946-02-15','1955-10-02',12);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM PC','1981-08-12',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Classic',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Classic II','1991-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga','1985-01-01',null,14);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 1000',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 500','1987-01-01',null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 500+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 2000','1986-01-01','1990-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 3000',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 600','1992-03-01',null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh 128K','1984-01-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh 512K','1984-09-10','1986-04-14',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh SE','1987-03-02','1989-08-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh SE/30','1989-01-19','1991-10-21',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Canon Cat','1987-01-01',null,15);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nokia 770',null,null,16);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nokia N800','2007-01-01',null,16);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Mylo','2006-09-21',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'OQO 02','2007-01-01',null,18);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'OQO 01+',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Pinwheel calculator',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iBook',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook','2006-05-16',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NeXTstation','1990-01-01','1993-01-01',19);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NeXTcube','1988-01-01','1993-01-01',19);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NeXTstation Color Turbo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NeXTstation Color',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NeXTstation Turbo',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NeXTcube Turbo',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NeXTcube 040',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NeXTcube 030',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Tinkertoy Tic-Tac-Toe Computer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Z3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Z4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Z1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Z2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Wang 2200','1973-05-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Wang VS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Wang OIS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'BBC Micro',null,null,22);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM 650','1953-01-01','1962-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray-1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray-3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray-2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray-4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray X1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray XD1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray T3D','1993-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray T3E','1995-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray C90',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray T90',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray SV1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray J90',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray XT3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray CS6400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari ST','1985-01-01','1993-01-01',20);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 2500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 2500',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 4000',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 3000UX',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 3000T',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 4000T',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 1200','1992-10-01','1996-01-01',6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 1040 STf','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 520 ST','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 520 STfm','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 1040 STe','1989-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari MEGA STe','1991-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 520 ST+','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 520 STm','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 130 ST','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 260 ST','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari MEGA ST','1987-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 520 STf','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 1040 STfm','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 2080 ST','1986-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 260 ST+','1985-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 4160 STe','1988-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TRS-80 Color Computer 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TRS-80 Color Computer 3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TRS-80 Model 1','1977-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Timex Sinclair 2068','1983-11-01','1984-04-01',23);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ZX Spectrum','1982-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Xerox Star','1981-01-01',null,26);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Xerox Alto',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Acorn Archimedes',null,null,22);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nintendo Entertainment System',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Super Nintendo Entertainment System','1991-08-01','1999-01-01',24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Super Famicom',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nintendo GameCube',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Game Boy line',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PlayStation','1994-12-03',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PlayStation 2','2000-03-24',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Game & Watch',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'EDSAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM System/4 Pi',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM AP-101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM TC-1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM AP-101B',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM AP-101S',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ProLiant',null,null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Http://nepomuk.semanticdesktop.org/xwiki/',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sinclair QL','1984-01-01','1986-01-01',25);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sinclair ZX81','1981-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sinclair ZX80',null,null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 65XE',null,null,20);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Deep Blue',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 650',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 610',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 800',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 950',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 160',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 145B',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 170',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 145',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 140',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh IIcx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Powerbook 180',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook G4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh XL',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 2400c',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 1400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 630',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 660AV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Quadra 840AV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 5300',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 3400c',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Color Classic',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh 512Ke',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh IIsi',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh IIx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 500 series',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh IIci',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iMac G5','2004-08-31',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Mac G4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 7100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 9600',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 7200',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 7300',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 8600',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 6200',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 8100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Compact Macintosh',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 4400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 9500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Portable',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'EMac',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 7600',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Mac G5',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 7500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 6100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 8500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh IIvi',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh IIvx',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IMac G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IMac G4',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Mac G4 Cube',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Intel iMac',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Deep Thought',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Wii','2006-11-19',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM System x',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM System i','2006-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM System z','2006-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM System p','2000-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'LC 575',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh TV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh Performa',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh II series',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 6400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 6500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple PenLite',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Wallstreet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Twentieth Anniversary Macintosh',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 5500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iBook G3',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 5200 LC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh 5400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CM-1',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MSX','1983-01-01','1995-01-01',28);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PlayStation 3',null,null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MSX2','1986-01-01',null,29);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MSX2+','1988-01-01',null,30);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MSX turbo R','1990-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Panasonic FS A1GT',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Panasonic FS A1ST',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-11',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-1',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-10',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-8',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-6',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DECSYSTEM-20',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-7',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-5',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-12',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'LINC',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-14',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-15',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PDP-16',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray X2','2007-01-01',null,31);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Cray X-MP','1982-01-01',null,31);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Evans & Sutherland ES-1',null,null,32);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore VIC-20','1980-01-01',null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerBook 150',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook Air','2008-01-15',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Digi-Comp I','1963-01-01',null,33);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Digi-Comp',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Digi-Comp II',null,null,33);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Manchester Mark I','1949-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Small-Scale Experimental Machine','1948-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nintendo 64',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Game Boy Advance',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Game Boy',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nintendo DS Lite',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nintendo DS','2004-01-01',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Game Boy Color',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Game Boy Advance SP',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Virtual Boy',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Game Boy Micro',null,null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Roadrunner',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HP 9000',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'OMRON Luna-88K2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'OMRON Luna-88K',null,null,34);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Motorola series 900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Motorola M8120',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Triton Dolphin System 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'BBN TC2000','1989-08-01',null,35);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'WRT54G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ThinkPad','1992-01-01',null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple Newton','1993-01-01','1998-01-01',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atanasoff-Berry Computer','1937-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atlas Computer','1962-01-01','1974-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASUS Eee PC 901',null,null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASUS Eee PC 701',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM 7030','1961-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'System/38','1979-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'System/36','1983-01-01','2000-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM 7090','1959-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM RT',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'System/360','1964-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM 801','1980-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM 1401','1959-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASCI White','2001-01-01','2006-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Blue Gene',null,null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASCI Blue Pacific','1998-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iPhone','2007-06-01',null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nokia N810','2007-10-17',null,16);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'EDSAC 2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Titan',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Pilot ACE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HP Mini 1000','2008-10-29',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HP 2133 Mini-Note PC','2008-04-15',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Kogan Agora Pro','2008-12-04',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'D-Series Machines',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ZX Spectrum 48K','1982-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ZX Spectrum 16K','1982-01-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ZX Spectrum 128','1985-09-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ZX Spectrum +3',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ZX Spectrum +2','1986-01-01',null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ZX Spectrum +2A','1987-01-01',null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ZX Spectrum +','1984-06-01',null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Acer Extensa',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Acer Extensa 5220',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Dell Latitude',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Toshiba Satellite',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Timex Sinclair 2048',null,null,23);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sprinter',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Timex Computer 2048',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Pentagon',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Belle',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Loki',null,null,25);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Hobbit',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NeXT Computer',null,null,19);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TRS-80',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TRS-80 Model 2','1980-01-01',null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TRS-80 Model 3',null,null,5);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'STacy','1989-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ST BOOK','1990-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari 520 STE','1989-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 2000 Model A',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 2000 Model B',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 2000 Model C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM 3270',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CALDIC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Modbook',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Compaq SystemPro',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ARRA',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM System Cluster 1350',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Finite element machine',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ES7000',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HP MediaSmart Server',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HP Superdome',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM Power Systems','2008-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Oslo Analyzer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Microsoft Softcard',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'WITCH',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Analytical engine',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'EDVAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'BINAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Earth Simulator',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'BARK',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Harvard Mark I','1944-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ILLIAC IV',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ILLIAC II',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ILLIAC III',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Water integrator',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CSIRAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'System X',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Harvest',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ChipTest',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HiTech',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Bomba',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ACE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASCI Red',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASCI Thors Hammer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASCI Purple','2005-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASCI Blue Mountain',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Columbia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HP Integrity',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'APEXC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Datasaab D2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'BRLESC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DYSEAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'SSEC','1948-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Hydra',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'FUJIC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'RAYDAC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Harvard Mark III',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DATAR',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ReserVec',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DASK',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'UTEC',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DRTE Computer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PowerEdge',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Apple Network Server',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Goodyear MPP',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Macintosh 128K technical details',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Power Macintosh G3',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CER-10',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CER-20',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM BladeCenter','2002-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Wisconsin Integrally Synchronized Computer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amstrad CPC',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amstrad CPC 6128',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amstrad CPC 664',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amstrad CPC 464',null,null,38);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Intergraph',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Enterprise',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MTX500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Acorn Electron',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sony Vaio P','2009-02-01',null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'VAIO',null,null,17);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sony Vaio P VGN-P588E/Q',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sony Vaio P VGN-P530H/G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sony Vaio P VGN-P530H/W',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sony Vaio P VGN-P530H/Q',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sony Vaio P VGN-P530H/R',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sony Vaio P VGN-P588E/R',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sony Vaio P VGN-P598E/Q',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Timex Sinclair 1000','1982-07-01',null,23);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Komputer 2086',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Galaksija',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Vector-06C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Elektronika BK',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sun386i',null,null,39);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Xerox Daybreak','1985-01-01','1989-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Xerox NoteTaker',null,null,26);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'D4a','1965-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'LGP-30',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'LGP-21',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASUS Eee PC 900','2008-05-01',null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Atari TT030',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Bi Am ZX-Spectrum 48/64',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Bi Am ZX-Spectrum 128',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PlayStation Portable',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MSI Wind Netbook',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sharp Mebius NJ70A','2009-04-21',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HTC Snap',null,null,41);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore Educator 64',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Amiga 1500',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore 65',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore 16',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore CBM-II',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore Plus/4',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore LCD',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Commodore MAX Machine',null,null,6);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Aster CT-80',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Test','2009-01-01','2009-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MSI GX723',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Eee PC 1000HV','2009-05-22',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'VTech Laser 200','1983-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CrunchPad',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Neo Geo','1990-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sega Mega Drive',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sega Master System',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'TurboGrafx-16',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Sun-3',null,null,39);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Pleiades',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM Sequoia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Inves Spectrum 48k plus',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iPhone 3G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iPhone 3GS',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Beagle Board',null,null,40);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HP nPar',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook Family',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Reservisor',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'BladeSystem',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad t60p',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad x200',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad t60',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad w700',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad t41',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad z61p',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad x61s',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad t43',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad r400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad x60s',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad x301',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad t42',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad r61',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad w500',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad sl400',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad x40',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad x200 tablet',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'lenovo thinkpad t400s',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nokia N900','2009-10-01',null,16);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Internet Tablet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Meiko Computing Surface','1986-01-01','1993-01-01',null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CS-2',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM 701','1952-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM 5100','1975-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'AN/FSQ-7','1958-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'AN/FSQ-32','1960-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM CPC','1949-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'System/34','1978-01-01','1983-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'System/32','1975-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'System/3','1969-01-01','1985-01-01',13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IBM 305','1956-01-01',null,13);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'English Electric DEUCE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CER-203',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'CER-22',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Kentucky Linux Athlon Testbed',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'QNAP TS-101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iPad','2010-01-01','2011-03-02',1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iPhone 2G',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Inslaw',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'WePad','2010-07-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook Parts',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240LL/A) DDR2 Model',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240T/A) DDR2 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook 13-inch Core 2 Duo 2.13GHz (MC240X/A) DDR2 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MacBook 13-inch Core 2 Duo 2.26GHz (Unibody MC207LL/A) DDR3 Model',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MC240LL/A',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'D.K.COMMUNICATION',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iPhone 4',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nintendo 3DS','2010-03-23',null,24);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ASUS Eee PC 1005PE','2010-01-01',null,37);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'National Law Enforcement System',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'BlackBerry PlayBook',null,null,42);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Barnes & Noble nook','2009-10-20',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'SAM Coupé',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HTC Dream','2008-10-22',null,41);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Samsung Galaxy Tab','2010-09-02',null,43);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'BlackBerry PlayBook','2010-09-27',null,42);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Tianhe-I',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Kno',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ThinkPad 701 C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ThinkPad 340 CSE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ThinkPad 755 CX',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ThinkPad 755 CE',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ThinkPad 370 C',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Coleco Adam','1983-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Nebulae',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Alex eReader',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Acer Iconia',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Archos 101',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Fujitsu Lifebook T900',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Motorola Xoom',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ViewSonic G Tablet',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC Professional','1982-01-01',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC Multia','1994-11-07',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC Firefly',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC 3000 AXP',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC 2000 AXP','1993-05-25',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC 4000 AXP','1992-11-10',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC 7000/10000 AXP','1992-11-10',null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC Professional 350',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC Rainbow 100',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC Professional 325',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DECmate II',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DECmate',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DECsystem',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'NetApp Filer',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'DEC GT40',null,null,10);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'ecoATM',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'MindWave BrainCubed Education Bundle',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'PalmPilot',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Upcoming iPhone 5',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Dell Inspiron 560 Desktop Computer ',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'IPad 2',null,null,1);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HP TouchPad','2011-02-09',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'HP Veer','2011-02-09',null,27);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Lenovo Thinkpad Edge 11',null,null,36);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Dell Vostro',null,null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'Gateway LT3103U','2008-01-01',null,null);
insert into computer (id,name,introduced,discontinued,company_id) values (default,'iPhone 4S','2011-10-14',null,1);

# --- !Downs

delete from computer;
delete from company;
